-- key_moves: auxiliary reference table
create table "public"."key_moves" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "name" text not null,
  "user_id" uuid not null default auth.uid()
);

alter table "public"."key_moves" enable row level security;

-- dances_key_moves: many-to-many junction
create table "public"."dances_key_moves" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "dance_id" bigint not null,
  "key_move_id" bigint not null
);

alter table "public"."dances_key_moves" enable row level security;

-- Primary keys
CREATE UNIQUE INDEX key_moves_pkey ON public.key_moves USING btree (id);
CREATE UNIQUE INDEX dances_key_moves_pkey ON public.dances_key_moves USING btree (id);

-- Unique name per user
CREATE UNIQUE INDEX key_moves_name_user_key ON public.key_moves USING btree (name, user_id);

-- FK indexes
CREATE INDEX ON public.key_moves (user_id);
CREATE INDEX ON public.dances_key_moves (dance_id);
CREATE INDEX ON public.dances_key_moves (key_move_id);

-- Constraints
alter table "public"."key_moves" add constraint "key_moves_pkey" PRIMARY KEY using index "key_moves_pkey";
alter table "public"."dances_key_moves" add constraint "dances_key_moves_pkey" PRIMARY KEY using index "dances_key_moves_pkey";

alter table "public"."key_moves" add constraint "key_moves_name_user_key" UNIQUE using index "key_moves_name_user_key";

alter table "public"."key_moves" add constraint "key_moves_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."key_moves" validate constraint "key_moves_user_id_fkey";

alter table "public"."dances_key_moves" add constraint "dances_key_moves_dance_id_fkey" FOREIGN KEY (dance_id) REFERENCES public.dances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."dances_key_moves" validate constraint "dances_key_moves_dance_id_fkey";

alter table "public"."dances_key_moves" add constraint "dances_key_moves_key_move_id_fkey" FOREIGN KEY (key_move_id) REFERENCES public.key_moves(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."dances_key_moves" validate constraint "dances_key_moves_key_move_id_fkey";

-- Grants
grant delete on table "public"."key_moves" to "anon";
grant insert on table "public"."key_moves" to "anon";
grant references on table "public"."key_moves" to "anon";
grant select on table "public"."key_moves" to "anon";
grant trigger on table "public"."key_moves" to "anon";
grant truncate on table "public"."key_moves" to "anon";
grant update on table "public"."key_moves" to "anon";

grant delete on table "public"."key_moves" to "authenticated";
grant insert on table "public"."key_moves" to "authenticated";
grant references on table "public"."key_moves" to "authenticated";
grant select on table "public"."key_moves" to "authenticated";
grant trigger on table "public"."key_moves" to "authenticated";
grant truncate on table "public"."key_moves" to "authenticated";
grant update on table "public"."key_moves" to "authenticated";

grant delete on table "public"."key_moves" to "postgres";
grant insert on table "public"."key_moves" to "postgres";
grant references on table "public"."key_moves" to "postgres";
grant select on table "public"."key_moves" to "postgres";
grant trigger on table "public"."key_moves" to "postgres";
grant truncate on table "public"."key_moves" to "postgres";
grant update on table "public"."key_moves" to "postgres";

grant delete on table "public"."key_moves" to "service_role";
grant insert on table "public"."key_moves" to "service_role";
grant references on table "public"."key_moves" to "service_role";
grant select on table "public"."key_moves" to "service_role";
grant trigger on table "public"."key_moves" to "service_role";
grant truncate on table "public"."key_moves" to "service_role";
grant update on table "public"."key_moves" to "service_role";

grant delete on table "public"."dances_key_moves" to "anon";
grant insert on table "public"."dances_key_moves" to "anon";
grant references on table "public"."dances_key_moves" to "anon";
grant select on table "public"."dances_key_moves" to "anon";
grant trigger on table "public"."dances_key_moves" to "anon";
grant truncate on table "public"."dances_key_moves" to "anon";
grant update on table "public"."dances_key_moves" to "anon";

grant delete on table "public"."dances_key_moves" to "authenticated";
grant insert on table "public"."dances_key_moves" to "authenticated";
grant references on table "public"."dances_key_moves" to "authenticated";
grant select on table "public"."dances_key_moves" to "authenticated";
grant trigger on table "public"."dances_key_moves" to "authenticated";
grant truncate on table "public"."dances_key_moves" to "authenticated";
grant update on table "public"."dances_key_moves" to "authenticated";

grant delete on table "public"."dances_key_moves" to "postgres";
grant insert on table "public"."dances_key_moves" to "postgres";
grant references on table "public"."dances_key_moves" to "postgres";
grant select on table "public"."dances_key_moves" to "postgres";
grant trigger on table "public"."dances_key_moves" to "postgres";
grant truncate on table "public"."dances_key_moves" to "postgres";
grant update on table "public"."dances_key_moves" to "postgres";

grant delete on table "public"."dances_key_moves" to "service_role";
grant insert on table "public"."dances_key_moves" to "service_role";
grant references on table "public"."dances_key_moves" to "service_role";
grant select on table "public"."dances_key_moves" to "service_role";
grant trigger on table "public"."dances_key_moves" to "service_role";
grant truncate on table "public"."dances_key_moves" to "service_role";
grant update on table "public"."dances_key_moves" to "service_role";

-- RLS policies
create policy "user_access"
on "public"."key_moves"
as permissive
for all
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy "user_access"
on "public"."dances_key_moves"
as permissive
for all
using (exists (
  select 1 from dances
  where dances.id = dance_id
  and dances.user_id = (select auth.uid())
));
