-- Shared lookup tables (no user_id — global, admin-managed via migrations)

-- dance_types
create table "public"."dance_types" (
  "id" bigint generated by default as identity not null,
  "name" text not null,
  "sort_order" integer not null
);

alter table "public"."dance_types" enable row level security;

CREATE UNIQUE INDEX dance_types_pkey ON public.dance_types USING btree (id);
CREATE UNIQUE INDEX dance_types_name_key ON public.dance_types USING btree (name);

alter table "public"."dance_types" add constraint "dance_types_pkey" PRIMARY KEY using index "dance_types_pkey";
alter table "public"."dance_types" add constraint "dance_types_name_key" UNIQUE using index "dance_types_name_key";

insert into "public"."dance_types" (name, sort_order) values
  ('Contra', 1),
  ('Circle Mixer', 2),
  ('Scatter Mixer', 3),
  ('ECD', 4),
  ('Other', 5);

-- formations
create table "public"."formations" (
  "id" bigint generated by default as identity not null,
  "name" text not null,
  "sort_order" integer not null
);

alter table "public"."formations" enable row level security;

CREATE UNIQUE INDEX formations_pkey ON public.formations USING btree (id);
CREATE UNIQUE INDEX formations_name_key ON public.formations USING btree (name);

alter table "public"."formations" add constraint "formations_pkey" PRIMARY KEY using index "formations_pkey";
alter table "public"."formations" add constraint "formations_name_key" UNIQUE using index "formations_name_key";

insert into "public"."formations" (name, sort_order) values
  ('Improper', 1),
  ('Becket', 2),
  ('Becket CCW', 3),
  ('Proper', 4),
  ('Indecent', 5),
  ('Four Facing Four', 6),
  ('Other', 7);

-- progressions
create table "public"."progressions" (
  "id" bigint generated by default as identity not null,
  "name" text not null,
  "sort_order" integer not null
);

alter table "public"."progressions" enable row level security;

CREATE UNIQUE INDEX progressions_pkey ON public.progressions USING btree (id);
CREATE UNIQUE INDEX progressions_name_key ON public.progressions USING btree (name);

alter table "public"."progressions" add constraint "progressions_pkey" PRIMARY KEY using index "progressions_pkey";
alter table "public"."progressions" add constraint "progressions_name_key" UNIQUE using index "progressions_name_key";

insert into "public"."progressions" (name, sort_order) values
  ('Single', 1),
  ('Double', 2),
  ('Triple', 3),
  ('None', 4),
  ('Other', 5);

-- FK columns on dances
alter table "public"."dances"
  add column "dance_type_id" bigint references public.dance_types(id) on delete set null,
  add column "formation_id" bigint references public.formations(id) on delete set null,
  add column "progression_id" bigint references public.progressions(id) on delete set null;

CREATE INDEX ON public.dances (dance_type_id);
CREATE INDEX ON public.dances (formation_id);
CREATE INDEX ON public.dances (progression_id);

-- Grants (read-only for all roles; writes managed via migrations)
grant select on table "public"."dance_types" to "anon";
grant select on table "public"."dance_types" to "authenticated";
grant select on table "public"."dance_types" to "postgres";
grant select on table "public"."dance_types" to "service_role";

grant select on table "public"."formations" to "anon";
grant select on table "public"."formations" to "authenticated";
grant select on table "public"."formations" to "postgres";
grant select on table "public"."formations" to "service_role";

grant select on table "public"."progressions" to "anon";
grant select on table "public"."progressions" to "authenticated";
grant select on table "public"."progressions" to "postgres";
grant select on table "public"."progressions" to "service_role";

-- RLS policies (select only for authenticated users)
create policy "authenticated_read"
on "public"."dance_types"
as permissive
for select
using (auth.role() = 'authenticated');

create policy "authenticated_read"
on "public"."formations"
as permissive
for select
using (auth.role() = 'authenticated');

create policy "authenticated_read"
on "public"."progressions"
as permissive
for select
using (auth.role() = 'authenticated');
