-- figures: one-to-many structured figure data per dance
create table "public"."figures" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "dance_id" bigint not null,
  "phrase" text not null,
  "order" smallint not null,
  "beats" smallint,
  "description" text not null
);

alter table "public"."figures" enable row level security;

-- Primary key
CREATE UNIQUE INDEX figures_pkey ON public.figures USING btree (id);

-- Composite index covers both FK lookups and ordered retrieval
CREATE INDEX ON public.figures (dance_id, "order");

-- Constraints
alter table "public"."figures" add constraint "figures_pkey" PRIMARY KEY using index "figures_pkey";

alter table "public"."figures" add constraint "figures_dance_id_fkey" FOREIGN KEY (dance_id) REFERENCES public.dances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."figures" validate constraint "figures_dance_id_fkey";

-- Grants
grant delete on table "public"."figures" to "anon";
grant insert on table "public"."figures" to "anon";
grant references on table "public"."figures" to "anon";
grant select on table "public"."figures" to "anon";
grant trigger on table "public"."figures" to "anon";
grant truncate on table "public"."figures" to "anon";
grant update on table "public"."figures" to "anon";

grant delete on table "public"."figures" to "authenticated";
grant insert on table "public"."figures" to "authenticated";
grant references on table "public"."figures" to "authenticated";
grant select on table "public"."figures" to "authenticated";
grant trigger on table "public"."figures" to "authenticated";
grant truncate on table "public"."figures" to "authenticated";
grant update on table "public"."figures" to "authenticated";

grant delete on table "public"."figures" to "postgres";
grant insert on table "public"."figures" to "postgres";
grant references on table "public"."figures" to "postgres";
grant select on table "public"."figures" to "postgres";
grant trigger on table "public"."figures" to "postgres";
grant truncate on table "public"."figures" to "postgres";
grant update on table "public"."figures" to "postgres";

grant delete on table "public"."figures" to "service_role";
grant insert on table "public"."figures" to "service_role";
grant references on table "public"."figures" to "service_role";
grant select on table "public"."figures" to "service_role";
grant trigger on table "public"."figures" to "service_role";
grant truncate on table "public"."figures" to "service_role";
grant update on table "public"."figures" to "service_role";

-- RLS policy
create policy "user_access"
on "public"."figures"
as permissive
for all
using (exists (
  select 1 from dances
  where dances.id = dance_id
  and dances.user_id = (select auth.uid())
));
