-- vibes: auxiliary reference table
create table "public"."vibes" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "name" text not null,
  "user_id" uuid not null default auth.uid()
);

alter table "public"."vibes" enable row level security;

-- dances_vibes: many-to-many junction
create table "public"."dances_vibes" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "dance_id" bigint not null,
  "vibe_id" bigint not null
);

alter table "public"."dances_vibes" enable row level security;

-- Primary keys
CREATE UNIQUE INDEX vibes_pkey ON public.vibes USING btree (id);
CREATE UNIQUE INDEX dances_vibes_pkey ON public.dances_vibes USING btree (id);

-- Unique name per user
CREATE UNIQUE INDEX vibes_name_user_key ON public.vibes USING btree (name, user_id);

-- FK indexes
CREATE INDEX ON public.vibes (user_id);
CREATE INDEX ON public.dances_vibes (dance_id);
CREATE INDEX ON public.dances_vibes (vibe_id);

-- Constraints
alter table "public"."vibes" add constraint "vibes_pkey" PRIMARY KEY using index "vibes_pkey";
alter table "public"."dances_vibes" add constraint "dances_vibes_pkey" PRIMARY KEY using index "dances_vibes_pkey";

alter table "public"."vibes" add constraint "vibes_name_user_key" UNIQUE using index "vibes_name_user_key";

alter table "public"."vibes" add constraint "vibes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."vibes" validate constraint "vibes_user_id_fkey";

alter table "public"."dances_vibes" add constraint "dances_vibes_dance_id_fkey" FOREIGN KEY (dance_id) REFERENCES public.dances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."dances_vibes" validate constraint "dances_vibes_dance_id_fkey";

alter table "public"."dances_vibes" add constraint "dances_vibes_vibe_id_fkey" FOREIGN KEY (vibe_id) REFERENCES public.vibes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."dances_vibes" validate constraint "dances_vibes_vibe_id_fkey";

-- Grants
grant delete on table "public"."vibes" to "anon";
grant insert on table "public"."vibes" to "anon";
grant references on table "public"."vibes" to "anon";
grant select on table "public"."vibes" to "anon";
grant trigger on table "public"."vibes" to "anon";
grant truncate on table "public"."vibes" to "anon";
grant update on table "public"."vibes" to "anon";

grant delete on table "public"."vibes" to "authenticated";
grant insert on table "public"."vibes" to "authenticated";
grant references on table "public"."vibes" to "authenticated";
grant select on table "public"."vibes" to "authenticated";
grant trigger on table "public"."vibes" to "authenticated";
grant truncate on table "public"."vibes" to "authenticated";
grant update on table "public"."vibes" to "authenticated";

grant delete on table "public"."vibes" to "postgres";
grant insert on table "public"."vibes" to "postgres";
grant references on table "public"."vibes" to "postgres";
grant select on table "public"."vibes" to "postgres";
grant trigger on table "public"."vibes" to "postgres";
grant truncate on table "public"."vibes" to "postgres";
grant update on table "public"."vibes" to "postgres";

grant delete on table "public"."vibes" to "service_role";
grant insert on table "public"."vibes" to "service_role";
grant references on table "public"."vibes" to "service_role";
grant select on table "public"."vibes" to "service_role";
grant trigger on table "public"."vibes" to "service_role";
grant truncate on table "public"."vibes" to "service_role";
grant update on table "public"."vibes" to "service_role";

grant delete on table "public"."dances_vibes" to "anon";
grant insert on table "public"."dances_vibes" to "anon";
grant references on table "public"."dances_vibes" to "anon";
grant select on table "public"."dances_vibes" to "anon";
grant trigger on table "public"."dances_vibes" to "anon";
grant truncate on table "public"."dances_vibes" to "anon";
grant update on table "public"."dances_vibes" to "anon";

grant delete on table "public"."dances_vibes" to "authenticated";
grant insert on table "public"."dances_vibes" to "authenticated";
grant references on table "public"."dances_vibes" to "authenticated";
grant select on table "public"."dances_vibes" to "authenticated";
grant trigger on table "public"."dances_vibes" to "authenticated";
grant truncate on table "public"."dances_vibes" to "authenticated";
grant update on table "public"."dances_vibes" to "authenticated";

grant delete on table "public"."dances_vibes" to "postgres";
grant insert on table "public"."dances_vibes" to "postgres";
grant references on table "public"."dances_vibes" to "postgres";
grant select on table "public"."dances_vibes" to "postgres";
grant trigger on table "public"."dances_vibes" to "postgres";
grant truncate on table "public"."dances_vibes" to "postgres";
grant update on table "public"."dances_vibes" to "postgres";

grant delete on table "public"."dances_vibes" to "service_role";
grant insert on table "public"."dances_vibes" to "service_role";
grant references on table "public"."dances_vibes" to "service_role";
grant select on table "public"."dances_vibes" to "service_role";
grant trigger on table "public"."dances_vibes" to "service_role";
grant truncate on table "public"."dances_vibes" to "service_role";
grant update on table "public"."dances_vibes" to "service_role";

-- RLS policies
create policy "user_access"
on "public"."vibes"
as permissive
for all
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy "user_access"
on "public"."dances_vibes"
as permissive
for all
using (exists (
  select 1 from dances
  where dances.id = dance_id
  and dances.user_id = (select auth.uid())
));
